### ISSUE TITLE
As a user I want a confirmation screen to appear to ensure I checked in to the right stations

### ISSUE THREAD

**Issue by danielqualitykitchen** [j0nscalet/QualityKitchen.Mobile#161] opened 2017-07-27 22:56 UTC
When the user taps the 'Checking in As ...' button, the 'Confirmation' screen will be displayed. On this screen the shift as well as a list of stations they've selected will be displayed so they can confirm their selection. If they've made a mistake they can tap 'No, that's not right' to go back to the 'Check In' screen to correct their mistakes.

https://user-images.githubusercontent.com/1328795/28576863-eb018ebc-7109-11e7-920d-2564834029c4.png

**Comment by j0nscalet** [comment] 2017-08-08 00:20
Duplicate of #160.

**Closed** 2017-08-08 00:20 UTC
